[[main]]
none = "none"

[[main]]
name = "Rólunk"
pageRef = "rolunk"
weight = 20

[[main]]
name = "Szatmári..."
pageRef = "szatmari/etelek"
weight = 30

    [[main]]
    name = "ételek"
    parent = "Szatmári..."
    pageRef = "szatmari/etelek"
    weight = 10

    [[main]]
    name = "néprajz"
    parent = "Szatmári..."
    pageRef = "feltoltes-alatt"
    weight = 20

[[main]]
name = "Táborok"
pageRef = "fotos-taborok"
weight = 30

    [[main]]
    name = "Fotós tábor"
    parent = "Táborok"
    pageRef = "fotos-taborok"
    weight = 10

    [[main]]
    name = "Kiégéstábor"
    parent = "Táborok"
    pageRef = "feltoltes-alatt"
    weight = 30

[[main]]
  name = "Mórucz-Kiss Klára ösztöndíjalap"
  pageRef = "feltoltes-alatt"
  weight = 40

[[main]]
  name = "Kapcsolat"
  pageRef = "kapcsolat"
  weight = 50

[[main]]
  name = "1%"
  pageRef = "egyszazalek"
  weight = 60

[[footer]]
  none = "none"
